---
stockPriceUrl: http://mm-recruitment-stock-price-api.herokuapp.com/company
tickerCodeMongoDb: mongodb://mm_recruitment_user_readonly:rebelMutualWhistle@ds037551.mongolab.com:37551/mm-recruitment

logging:
  level: WARN
  loggers:
    mergermarkets: DEBUG
  appenders:
    - type: console

assets:
  mappings:
    /app: /app
  overrides:
    /app: src/main/resources/webapp/app/
    /app/bower_components: src/main/resources/webapp/bower_components/